#!/usr/bin/env bash
#script that displays the content of the current directory in a list format
#Displaying the part of the name after the first dash

i=$(ls)
for i in $i; do
	echo "$i" | cut -d "-" -f2
done
