#!/usr/bin/env bash
#script that displays the content of the current directory in a list format
#Displaying the part of the name after the first dash

for file in *; do
	if [[ $file == *-* ]]; then
		echo "${file#*-}"
	fi
done
